export const CLIENT_ID_DEV = 'dev_saleslog.theklab.fd8bbf18dd1d98d684dae3a711ada761';
export const CLIENT_ID_PROD = 'saleslog.theklab.fd8bbf18dd1d98d684dae3a711ada761'
/* AUTH */
export const AUTHORIZE_REQUEST = 'AUTHORIZE_REQUEST';
export const AUTHORIZE_REQUEST_SUCCESS = 'AUTHORIZE_REQUEST_SUCCESS';
export const AUTHORIZE_REQUEST_FAIL = 'AUTHORIZE_REQUEST_FAIL';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
export const SIGN_OUT_USER_SUCCESS = 'SIGN_OUT_USER_SUCCESS';
export const SIGN_OUT_USER_FAIL = 'SIGN_OUT_USER_FAIL';
export const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN';
export const GET_REFRESH_TOKEN = 'GET_REFRESH_TOKEN';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
//AUTH_RENWEAL
export const OAUTH_AUTHORIZE = 'OAUTH_AUTHORIZE';
export const OAUTH_AUTHORIZE_SUCCESS = 'OAUTH_AUTHORIZE_SUCCESS';
export const OAUTH_AUTHORIZE_ERROR = 'OAUTH_AUTHORIZE_ERROR';
export const GET_OAUTH_TOKEN = 'GET_OAUTH_TOKEN';
export const GET_REFRESH_OAUTH_TOKEN = 'GET_REFRESH_OAUTH_TOKEN';
export const POST_AUTHNUMBER = 'POST_AUTHNUMBER';
export const POST_AUTHNUMBER_SUCCESS = 'POST_AUTHNUMBER_SUCCESS';
export const POST_AUTHNUMBER_ERROR = 'POST_AUTHNUMBER_ERROR';
export const POST_REGISTRATION = 'POST_REGISTRATION';
export const POST_REGISTRATION_SUCCESS = 'POST_REGISTRATION_SUCCESS';
export const POST_REGISTRATION_ERROR = 'POST_REGISTRATION_ERROR';
export const POST_INVITE = 'POST_INVITE';
export const POST_INVITE_SUCCESS = 'POST_INVITE_SUCCESS';
export const POST_INVITE_ERROR = 'POST_INVITE_ERROR';
export const POST_INVITE_REGISTRATION = 'POST_INVITE_REGISTRATION';
export const POST_INVITE_REGISTRATION_SUCCESS = 'POST_INVITE_REGISTRATION_SUCCESS';
export const POST_INVITE_REGISTRATION_ERROR = 'POST_INVITE_REGISTRATION_ERROR';


// AUTH_SSO
export const OAUTH_AUTHENTICATE_USER = 'OAUTH_AUTHENTICATE_USER';
export const OAUTH_AUTHENTICATE_USER_SUCCESS = 'OAUTH_AUTHENTICATE_USER_SUCCESS';
export const OAUTH_AUTHENTICATE_USER_FAILED = 'OAUTH_AUTHENTICATE_USER_FAILED';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILED = 'SIGNUP_USER_FAILED';

export const CHECK_EMAIL = 'CHECK_EMAIL';
export const NOT_EXIST = 'NOT_EXIST';
export const ALREADY_EXIST = 'ALREADY_EXIST';
export const INIT_FORM = 'INIT_FORM';

export const POST_USER = 'POST_USER';
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS';
export const POST_USER_FAILED = 'POST_USER_FAILED';

export const SIGNOUT_USER = 'SIGNOUT_USER';

export const SET_POLICY_CHECK = 'SET_POLICY_CHECK';
export const SET_USER_TYPE = 'SET_USER_TYPE';
export const SET_USER_FORM = 'SET_USER_FORM';
export const SIGN_UP_COMPLETE = 'SIGN_UP_COMPLETE';

export const FIND_PASSWORD = 'FIND_PASSWORD';
export const FIND_PASSWORD_SUCCESS = 'FIND_PASSWORD_SUCCESS';
export const FIND_PASSWORD_FAILED = 'FIND_PASSWORD_FAILED';

/* USER */
export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const GET_USER_TREE = 'GET_USER_TREE';

/* NAV */
export const CHANGE_MENU = 'CHANGE_MENU';
export const CHANGE_SUB_MENU = 'CHANGE_SUB_MENU';
export const CHANGE_TAB = 'CHANGE_TAB';
export const CHANGE_SUB_TAB = 'CHANGE_SUB_TAB';

/* ACCOUNT  */
export const GET_USER_ACCOUNT = 'GET_USER_ACCOUNT';
export const GET_USER_ACCOUNT_SUCCESS = 'GET_USER_ACCOUNT_SUCCESS';
export const GET_USER_ACCOUNT_ERROR = 'GET_USER_ACCOUNT_ERROR';

/* SALESLOG */
export const POST_SALESLOG = 'POST_SALESLOG';
export const POST_SALESLOG_SUCCESS = 'POST_SALESLOG_SUCCESS';
export const POST_SALESLOG_BATCH_ASYNC = 'POST_SALESLOG_BATCH_ASYNC';
export const POST_SALESLOG_BATCH_STATUS = 'POST_SALESLOG_BATCH_STATUS';
export const PUT_SALESLOG = 'PUT_SALESLOG';
export const PUT_SALESLOG_SUCCESS = 'PUT_SALESLOG_SUCCESS';
export const GET_SALESLOG = 'GET_SALESLOG';
export const GET_SALESLOG_SUCCESS = 'GET_SALESLOG_SUCCESS';
export const GET_SALESLOGS = 'GET_SALESLOGS';
export const GET_NOTABLE_SALESLOGS = 'GET_NOTABLE_SALESLOGS';
export const PUT_NOTABLE_SALESLOG = 'GET_NOTABLE_SALESLOG';
export const GET_SALESLOG_ASYNC_STATUS = 'GET_SALESLOG_ASYNC_STATUS';
export const GET_SALESLOG_ASYNC_STATUS_SUCCESS = 'GET_SALESLOG_ASYNC_STATUS_SUCCESS';
export const GET_SALESLOG_POC = 'GET_SALESLOG_POC';
export const GET_SALESLOG_POC_SUCCESS = 'GET_SALESLOG_POC_SUCCESS'
export const GET_USER_SALESLOG = 'GET_USER_SALESLOG';
export const GET_USER_SALESLOG_SUCCESS = 'GET_USER_SALESLOG_SUCCESS';
export const GET_SALESLOG_WITH_ID = 'GET_SALESLOG_WITH_ID';
export const GET_SALESLOG_WITH_ID_SUCCESS = 'GET_SALESLOG_WITH_ID_SUCCESS';
export const DELETE_SALESLOG = 'DELETE_SALESLOG';
export const DELETE_SALESLOG_SUCCESS = 'DELETE_SALESLOG_SUCCESS';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const DELETE_GROUP_NOTIFICATION = 'DELETE_GROUP_NOTIFICATION';
export const DELETE_GROUP_NOTIFICATION_SUCCESS = 'DELETE_GROUP_NOTIFICATION_SUCCESS';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';
export const REQUEST_FAIL = 'REQUEST_FAIL';
export const GET_SALESLOG_FILE = 'GET_SALESLOG_FILE';
export const POST_SALESLOG_FILE_URL = 'POST_SALESLOG_FILE_URL'
export const POST_SALESLOG_FILE = 'POST_SALESLOG_FILE';
export const POST_SALESLOG_FILE_SUCCESS = 'POST_SALESLOG_FILE_SUCCESS';
export const GET_SALESLOG_REPORT = 'GET_SALESLOG_REPORT';
export const GET_SALESLOG_REPORT_SUCCESS = 'GET_SALESLOG_REPORT_SUCCESS';
export const GET_ACCOUNT_REPORT = 'GET_ACCOUNT_REPORT';
export const GET_ACCOUNT_REPORT_SUCCESS = 'GET_ACCOUNT_REPORT_SUCCESS';
export const PUT_SALESLOG_COUSER = 'PUT_SALESLOG_COUSER';
export const PUT_SALESLOG_COUSER_SUCCESS = 'PUT_SALESLOG_COUSER_SUCCESS';
export const PUT_SALESLOG_COUSER_ERROR = 'PUT_SALESLOG_COUSER_ERROR';
export const PUT_SALESLOG_GUIDE = 'PUT_SALESLOG_GUIDE';
export const PUT_SALESLOG_GUIDE_SUCCESS = 'PUT_SALESLOG_GUIDE';
export const PUT_SALESLOG_GUIDE_ERROR = 'PUT_SALESLOG_GUIDE';
export const DELETE_SALESLOG_GUIDE = 'DELETE_SALESLOG_GUIDE';
export const DELETE_SALESLOG_GUIDE_SUCCESS = 'DELETE_SALESLOG_GUIDE';
export const DELETE_SALESLOG_GUIDE_ERROR = 'DELETE_SALESLOG_GUIDE';
export const GET_SALESLOG_NEEDS = 'GET_SALESLOG_NEEDS';
export const GET_SALESLOG_NEEDS_SUCCESS = 'GET_SALESLOG_NEEDS_SUCCESS';
export const GET_SALESLOG_NEEDS_ERROR = 'GET_SALESLOG_NEEDS_ERROR';

export const CONCAT_LOG = 'CONCAT_LOG';
export const CLEAR_SALESLOG = 'CLEAR_SALESLOG';
export const CLEAR_SALESLOGS = 'CLEAR_SALESLOGS';
export const CLEAR_POST_SALESLOG_RESPONSE = 'CLEAR_POST_SALESLOG_RESPONSE';
export const UPDATE_FILTERED_SALESLOG = 'UPDATE_FILTERED_SALESLOG';
export const UPDATE_FILTERED_SALESLOG_SUCCESS = 'UPDATE_FILTERED_SALESLOG_SUCCESS';
export const SEARCH_SALESLOG = 'SEARCH_SALESLOG';
export const UPDATE_SEARCHED_SALESLOG_SUCCESS = 'UPDATE_SEARCHED_SALESLOG_SUCCESS';
export const GET_SEARCH_SALESLOG = 'GET_SEARCH_SALESLOG';

/* STAT */
export const GET_DASHBOARD_STAT = 'GET_DASHBOARD_STAT';
export const GET_STAT_TYPE1 = 'GET_STAT_TYPE1';
export const GET_STAT_TYPE2 = 'GET_STAT_TYPE2';
export const GET_STAT_TYPE3 = 'GET_STAT_TYPE3';
export const GET_STAT_TYPE4 = 'GET_STAT_TYPE4';
export const GET_STAT_TYPE5 = 'GET_STAT_TYPE5';
export const GET_SALES_LOG_SHEET = 'GET_SALES_LOG_SHEET';

/* NOTIFICATION */
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const PUT_NOTIFICATION = 'PUT_NOTIFICATION';
export const GET_ENTITY_NOTIFICATIONS = 'GET_ENTITY_NOTIFICATIONS';

/* COMMENTS */
export const GET_SALESLOG_COMMENT = 'GET_SALESLOG_COMMENT';
export const GET_SALESLOG_COMMENT_SUCCESS = 'GET_SALESLOG_COMMENT_SUCCESS';
export const POST_COMMENT = 'POST_COMMENT';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';

/* ORGANIZATION */
export const GET_ORGANIZATION = 'GET_ORGANIZATION';
export const GET_USERS = 'GET_USERS';

/* FILTER */
export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const SET_USERS = 'SET_USERS';
export const ON_DELETED_USER = 'ON_DELETED_USER';
export const SET_FROM_DATE = 'SET_FROM_DATE';
export const SET_TO_DATE = 'SET_TO_DATE';
export const SET_PAGE = 'SET_PAGE';

// Board
export const REGISTER_ARTICLE = 'REGISTER_ARTICLE';
export const GET_ARTICLE = 'GET_ARTICLE';
export const GET_ARTICLES = 'GET_ARTICLES';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const PUT_ARTICLE = 'PUT_ARTICLE';
export const POST_ARTICLE_COMMENT = 'POST_ARTICLE_COMMENT';
export const GET_FILTER_ARTICLES = 'GET_FILTER_ARTICLES';
export const FILTER_CONCAT_LOG = 'FILTER_CONCAT_LOG';
export const CLEAR_FILTER_ARTICLES = 'CLEAR_FILTER_ARTICLES'

//BoardFilter
export const SET_FILTER_USERS = 'SET_FILTER_USERS';
export const SET_FILTER_FROM_DATE = 'SET_FILTER_FROM_DATE';
export const SET_FILTER_TO_DATE = 'SET_FILTER_TO_DATE';
export const SET_FILTER_PAGE = 'SET_FILTER_PAGE';
export const SET_FILTER_ORDER = 'SET_FILTER_ORDER';
export const SET_BOARD_RADIOBOX = 'SET_BOARD_RADIOBOX';

//TripReport
export const GET_TRIPS_SALESLOG = 'GET_TRIPS_SALESLOG';
export const POST_TRIP_SALESLOG = 'POST_TRIP_SALESLOG';
export const GET_TRIP_SALESLOG = 'GET_TRIP_SALESLOG';
export const PUT_TRIP_SALESLOG = 'PUT_TRIP_SALESLOG';
export const DELETE_TRIP_SALESLOG = 'DELETE_TRIP_SALESLOG';
