

// RENEWAL

//AUTH
export const OAUTH_AUTHORIZE = 'OAUTH_AUTHORIZE'; //인증코드 가져오기
export const OAUTH_AUTHORIZE_SUCCESS = 'OAUTH_AUTHORIZE_SUCCESS';
export const OAUTH_AUTHORIZE_ERROR = 'OAUTH_AUTHORIZE_ERROR';

export const GET_OAUTH_TOKEN = 'GET_OAUTH_TOKEN'; //엑세스 토큰 가져오기
export const GET_OAUTH_TOKEN_SUCCESS = 'GET_OAUTH_TOKEN_SUCCESS';
export const GET_OAUTH_TOKEN_ERROR = 'GET_OAUTH_TOKEN_ERROR';

export const GET_REFRESH_OAUTH_TOKEN = 'GET_REFRESH_OAUTH_TOKEN'; //리프레쉬 토큰 가져오기

// export const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';//비밀번호 변경
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERRPR = 'CHANGE_PASSWORD_ERRPR';

export const FIND_PASSWORD = 'FIND_PASSWORD'; // 비밀번호 찾기
export const FIND_PASSWORD_SUCCESS = 'FIND_PASSWORD_SUCCESS';
export const FIND_PASSWORD_FAILED = 'FIND_PASSWORD_FAILED';

export const POST_AUTHNUMBER = 'POST_AUTHNUMBER'; //인증번호 가져오기
export const POST_AUTHNUMBER_SUCCESS = 'POST_AUTHNUMBER_SUCCESS';
export const POST_AUTHNUMBER_ERROR = 'POST_AUTHNUMBER_ERROR';

export const POST_REGISTRATION = 'POST_REGISTRATION'; //신규 회원가입
export const POST_REGISTRATION_SUCCESS = 'POST_REGISTRATION_SUCCESS';
export const POST_REGISTRATION_ERROR = 'POST_REGISTRATION_ERROR';

export const POST_INVITE = 'POST_INVITE'; //회원 초대메일
export const POST_INVITE_SUCCESS = 'POST_INVITE_SUCCESS';
export const POST_INVITE_ERROR = 'POST_INVITE_ERROR';

export const POST_INVITE_REGISTRATION = 'POST_INVITE_REGISTRATION'; //초대 했을 때의 회원가입
export const POST_INVITE_REGISTRATION_SUCCESS = 'POST_INVITE_REGISTRATION_SUCCESS';
export const POST_INVITE_REGISTRATION_ERROR = 'POST_INVITE_REGISTRATION_ERROR';

export const POST_WORKGROUP = 'POST_WORKGROUP'; //워크그룹 생성
export const POST_WORKGROUP_SUCCESS = 'POST_WORKGROUP_SUCCESS';
export const POST_WORKGROUP_ERROR = 'POST_WORKGROUP_ERROR';

//워크그룹 있는지 체크 작업 해야됨.


/* SALESLOG */
export const POST_TEMPORARY_SALESLOG = 'POST_TEMPORARY_SALESLOG';   //영업일지 임시저장 등록
export const POST_TEMPORARY_SALESLOG_SUCCESS = 'POST_TEMPORARY_SALESLOG_SUCCESS';
export const POST_TEMPORARY_SALESLOG_ERROR = 'POST_TEMPORARY_SALESLOG_ERROR';

export const POST_SALESLOG = 'POST_SALESLOG';   //영업일지 등록
export const POST_SALESLOG_SUCCESS = 'POST_SALESLOG_SUCCESS';
export const POST_SALESLOG_ERROR = 'POST_SALESLOG_ERROR';

export const POST_SALESLOG_BATCH_ASYNC = 'POST_SALESLOG_BATCH_ASYNC';
export const POST_SALESLOG_BATCH_STATUS = 'POST_SALESLOG_BATCH_STATUS';

export const PUT_SALESLOG = 'PUT_SALESLOG'; //영업일지 수정
export const PUT_SALESLOG_SUCCESS = 'PUT_SALESLOG_SUCCESS';
export const PUT_SALESLOG_ERROR = 'PUT_SALESLOG_ERROR';

export const SEARCH_SALESLOG_LIST = 'SEARCH_SALESLOG'; //영업일지 검색
export const SEARCH_SALESLOG_LIST_SUCCESS = 'SEARCH_SALESLOG_SUCCESS';
export const SEARCH_SALESLOG_LIST_ERROR = 'SEARCH_SALESLOG_ERROR';

export const GET_SALESLOG = 'GET_SALESLOG';  //영업일지 상세
export const GET_SALESLOG_SUCCESS = 'GET_SALESLOG_SUCCESS';
export const GET_SALESLOG_ERROR = 'GET_SALESLOG_ERROR';

export const GET_SALESLOGS = 'GET_SALESLOGS'; // 영업일지 리스트들 불러오기(백엔드 작업 안된듯 확인 필요)
export const GET_SALESLOGS_SUCCESS = 'GET_SALESLOGS_SUCCESS';
export const GET_SALESLOGS_ERROR = 'GET_SALESLOGS_ERROR';

export const UPLOAD_FILE = 'UPLOAD_FILE'; // 파일 업로드
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR';


/* ACCOUNT  */
export const SELECT_ACCOUNTS = 'SELECT_ACCOUNT';  // 고객사 선택
export const SELECT_ACCOUNTS_SUCCESS = 'SELECT_ACCOUNT_SUCCESS';
export const SELECT_ACCOUNTS_ERROR = 'SELECT_ACCOUNT_ERROR';
export const POST_ACCOUNTS = 'POST_ACCOUNTS';  // 고객사 등록
export const POST_ACCOUNTS_SUCCESS = 'POST_ACCOUNTS_SUCCESS';
export const POST_ACCOUNTS_ERROR = 'POST_ACCOUNTS_ERROR';
export const PUT_ACCOUNTS = 'PUT_ACCOUNTS';  // 고객사 수정
export const PUT_ACCOUNTS_SUCCESS = 'PUT_ACCOUNTS_SUCCESS';
export const PUT_ACCOUNTS_ERROR = 'PUT_ACCOUNTS_ERROR';
export const SELECT_ACCOUNT_PERSON = 'SELECT_ACCOUNT_PERSON';  //고객 담당자 선택
export const SELECT_ACCOUNT_PERSON_SUCCESS = 'SELECT_ACCOUNT_PERSON_SUCCESS';
export const SELECT_ACCOUNT_PERSON_ERROR = 'SELECT_ACCOUNT_PERSON_ERROR';
export const POST_ACCOUNT_PERSON = 'POST_ACCOUNT_PERSON';  //고객 담당자 등록
export const POST_ACCOUNT_PERSON_SUCCESS = 'POST_ACCOUNT_PERSON_SUCCESS';
export const POST_ACCOUNT_PERSON_ERROR = 'POST_ACCOUNT_PERSON_ERROR';
export const PUT_ACCOUNT_PERSON = 'PUT_ACCOUNT_PERSON';  //고객 담당자 수정
export const PUT_ACCOUNT_PERSON_SUCCESS = 'PUT_ACCOUNT_PERSON_SUCCESS';
export const PUT_ACCOUNT_PERSON_ERROR = 'PUT_ACCOUNT_PERSON_ERROR';



//기존 것
//ACCOUNT
export const GET_USER_ACCOUNT = 'GET_USER_ACCOUNT';
export const GET_USER_ACCOUNT_SUCCESS = 'GET_USER_ACCOUNT_SUCCESS';
export const GET_USER_ACCOUNT_ERROR = 'GET_USER_ACCOUNT_ERROR';
